### ISSUE TITLE
drop.lol as PWA

### ISSUE THREAD

**Issue by EmilienD** [mat-sz/filedrop#12]
I installed drop.lol on my phone but I would really like it to show a proper icon. Would you be interested in a PR that turns the client into a PWA?

Edit:
Lighthouse report:
- Manifest does not contain a 'name' or 'short_name' field
- Manifest does not contain a suitable icon - PNG, SVG or WebP format of at least 144 px is required, the sizes attribute must be set, and the purpose attribute, if set, must include "any".
- No matching service worker detected. You may need to reload the page, or check that the scope of the service worker for the current page encloses the scope and start URL from the manifest.
- No supplied icon is at least 144 px square in PNG, SVG or WebP format, with the purpose attribute unset or set to "any"

**Comment by mat-sz** [comment]
@EmilienD Added all except for service worker.
