### ISSUE TITLE
Reported as unsafe website

### ISSUE THREAD

**Issue by nereuseng** [mat-sz/filedrop#19]
Hi team, just to let you know that on macOS Microsoft Edge, the page was marked as unsafe page. Should it be still considered as safe website?

Thanks for the work of this project, I really love it!

Here is the screenshot of it:
![image](https://user-images.githubusercontent.com/11313394/211350452-5d52f474-57fc-482d-a007-c5f424aabf76.png)

**Comment by mat-sz** [comment]
@nereuseng That's odd. As far as I know everything on my end is working as usual and the server has not been breached into. The files have not been modified since the recent update.

I'll reach out to Microsoft, thank you for bringing this to my attention.

**Comment by nereuseng** [comment]
Thanks a lot!

**Comment by mat-sz** [comment]
@nereuseng Could you check if the issue still persists? I'm testing on my PC and I see no such warnings.
