### ISSUE TITLE
Adding swipe gesture to scroll the page

### ISSUE THREAD

**Issue by IneHi** [mat-sz/filedrop#28]
First of all, thanks for building this amazing service.

I'm an Android user and I'm trying to find a way that allows sending pictures between iPhone and Android phones without downloading any apps and the signing up stuff. Basically I'm finding a way to do what Airdrop does. This one get the best experience of all the stuff I've been tried.

I noticed that I can't scroll the page by swiping the screen , the only way to scroll the page is to drag the scroll bar.
I've tried three different browsers, Samsung Internet, Chrome and Brave , it shows the same behavior.

So I was wondering if you could add swiping into the methods of scrolling the page?

**Comment by mat-sz** [comment]
@IneHi Thank you for your report, the issue should now be resolved.

Please let me know if the problem persists.

**Comment by IneHi** [comment]
Excellent! It works smoothly now, thanks for the fix
