### ISSUE TITLE
Can't access from WAN

### ISSUE THREAD

**Issue by ManuXD32** [mat-sz/filedrop#29]
Hey, maybe there's something i'm not seeing, but when I try to access the server from outside my LAN, i can't get it to work, it doesn't even connect.

I'm using the docker compose file for deployment, set the port to 32768 and allowed it through the firewall, I've tried accessing with my public ip and exposing that port and also through the nginx reverse proxy with the config you provided (except the http3 part as my built doesn't have that module).

Is there anything I'm missing here? Thanks in advance.

**Comment by mat-sz** [comment]
Running on home networks is not recommended, it's likely that your ISP is blocking some of the required ports or that you're simply not forwarding TURN ports.

Anyway, this is not an issue related to the project; please do not reopen this issue.

**Comment by ManuXD32** [comment]
Okay, thanks
